/**
 * Build the IL place-name gazetteer used by worker/lib/normalizer.ts.
 *
 * Reads a single-column CSV of Israeli city / region names (header row "city")
 * and emits worker/data/il-places.ts with two deduped arrays:
 *   - IL_REGIONS  (broad areas; rows like "אזור צפון" -> "צפון")
 *   - IL_CITIES   (everything else, verbatim)
 *
 * Region detection: a row is a region when it starts with "אזור " (with a
 * space) AND does not contain "תעשיה"/"תעשייה" (those are industrial-zone
 * place names, e.g. "אזור תעשיה ברקן", which stay cities). The bare row
 * "אזור" (the town Azor) also stays a city. The "אזור " prefix is stripped so
 * the stored region is e.g. "צפון" / "רמת הגולן".
 *
 * The current built-in seed lists are merged in so nothing regresses if the
 * CSV omits a spelling variant we already relied on.
 *
 * Run:  npx tsx scripts/build-il-places.ts
 */
import * as fs from "fs";
import * as path from "path";

const CSV_PATH = path.resolve("CSV files", "city.csv");
const OUT_PATH = path.resolve("worker", "data", "il-places.ts");

// Seed lists previously hardcoded in normalizer.ts — merged so we never lose a
// spelling variant the rest of the pipeline already depended on.
const SEED_REGIONS = [
  "השפלה", "השרון", "הצפון", "הדרום", "המרכז", "הגליל", "הנגב", "הכרמל",
];
const SEED_CITIES = [
  "פתח תקווה", "פתח-תקווה", "קריית אריה", "קרית אריה", "תל אביב", 'ת"א',
  "ירושלים", "חיפה", "באר שבע", "ראשון לציון", "נתניה", "רמת גן", "חולון",
  "רחובות", "הרצליה", "כפר סבא", "רעננה", "מודיעין", "אשדוד", "אשקלון",
  "בת ים", "לוד", "רמלה", "הוד השרון", "כפר יונה", "יבנה", "קרית שמונה",
  "קריית שמונה", "טבריה", "נהריה", "עכו", "קרית ביאליק", "קריית ביאליק",
  "קרית מוצקין", "קריית מוצקין", "קרית ים", "קריית ים", "אילת", "אריאל",
  "מעלה אדומים", "בני ברק", "גבעתיים", "הרצלייה", "גדרה", "יהוד", "אור יהודה",
  "אלעד", "ראש העין", "חדרה", "זכרון יעקב", "עפולה", "נצרת", "טירת כרמל",
  "דימונה", "ערד", "קרית גת", "קריית גת",
];

function normalizeRow(raw: string): string {
  return raw.replace(/^\uFEFF/, "").replace(/[\r\n]+$/, "").trim();
}

function main(): void {
  const text = fs.readFileSync(CSV_PATH, "utf8");
  const rows = text.split(/\r?\n/);

  const regions = new Set<string>(SEED_REGIONS);
  const cities = new Set<string>(SEED_CITIES);

  let header = true;
  let cityCount = 0;
  let regionCount = 0;
  for (const rawRow of rows) {
    const row = normalizeRow(rawRow);
    if (!row) continue;
    if (header) {
      header = false;
      // Skip an obvious header cell; otherwise treat as data.
      if (/^city$/i.test(row)) continue;
    }
    const isRegion = /^אזור\s+\S/.test(row) && !/תעשי[יה]ה?/.test(row);
    if (isRegion) {
      const name = row.replace(/^אזור\s+/, "").trim();
      if (name.length >= 2) {
        regions.add(name);
        regionCount++;
      }
    } else if (row.length >= 2) {
      cities.add(row);
      cityCount++;
    }
  }

  // Longest first so multi-word names win in a regex alternation.
  const byLenDesc = (a: string, b: string) =>
    b.length - a.length || a.localeCompare(b, "he");
  const cityList = Array.from(cities).sort(byLenDesc);
  const regionList = Array.from(regions).sort(byLenDesc);

  const fmt = (arr: string[]) =>
    arr.map((s) => `  ${JSON.stringify(s)},`).join("\n");

  const out = `// AUTO-GENERATED by scripts/build-il-places.ts — DO NOT EDIT BY HAND.
// Source: "CSV files/city.csv" (+ seed variants from the former inline list).
// Regenerate with:  npx tsx scripts/build-il-places.ts
//
// Arrays are sorted longest-name-first so that, when joined into a single
// regex alternation, a more specific multi-word place (e.g. "ראשון לציון")
// wins over a shorter substring (e.g. "ראשון") at the same position.

export const IL_REGIONS: readonly string[] = [
${fmt(regionList)}
];

export const IL_CITIES: readonly string[] = [
${fmt(cityList)}
];
`;

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, out, "utf8");
  console.log(
    `wrote ${OUT_PATH}\n  cities: ${cityList.length} (from CSV: ${cityCount}, +seed)` +
      `\n  regions: ${regionList.length} (from CSV: ${regionCount}, +seed)`,
  );
}

main();
